/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.UserDirectory;
import model.Person;

/**
 *
 * @author navdishbatra
 */

public class ManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageJPanel
     */
    private JPanel userProcessArea;
    private UserDirectory UserDirectory;
    public ManageJPanel(JPanel userProcessArea, UserDirectory UserDirectory) {
        initComponents();
        System.out.println(UserDirectory.getUserList().size());
        this.userProcessArea = userProcessArea;
        this.UserDirectory = UserDirectory;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchIdTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        BackMButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        displayUsernameTxt = new javax.swing.JTextField();
        displayPasswordTxt = new javax.swing.JTextField();
        displayNUIDTxt = new javax.swing.JTextField();
        displayUseridTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password", "NUID", "UserId"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        BackMButton.setText("<<Back");
        BackMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMButtonActionPerformed(evt);
            }
        });

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password", "NUID", "userId"
            }
        ));
        jScrollPane2.setViewportView(UserTable);

        jLabel2.setText("Username:");

        jLabel3.setText("Password");

        jLabel4.setText("NUID:");

        jLabel5.setText("UserId:");

        displayNUIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayNUIDTxtActionPerformed(evt);
            }
        });

        displayUseridTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayUseridTxtActionPerformed(evt);
            }
        });

        jButton1.setText("Update & Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackMButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ViewBtn)
                                    .addComponent(UpdateBtn))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(displayPasswordTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(displayNUIDTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(displayUseridTxt, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(37, 37, 37)
                                        .addComponent(displayUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(173, 173, 173)))
                .addGap(163, 163, 163))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(327, 327, 327))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewBtn)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(displayUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(displayPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(displayNUIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayUseridTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackMButton)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = UserTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        var selectedPerson =(Person)model.getValueAt(selectedRowIndex, 0);
        
        displayUsernameTxt.setText(String.valueOf(selectedPerson.getUsername()));
        displayPasswordTxt.setText(String.valueOf(selectedPerson.getPassword()));
        displayNUIDTxt.setText(String.valueOf(selectedPerson.getNUID()));
        displayUseridTxt.setText(selectedPerson.getUserid());
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void displayUseridTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayUseridTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayUseridTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        //     null;
            
     
    }//GEN-LAST:event_searchBtnActionPerformed

    private void displayNUIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayNUIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayNUIDTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String newusername =  displayUsernameTxt.getText();
       String newpassword = displayPasswordTxt.getText();
       String newnuid = displayNUIDTxt.getText();
       String newuserid =  displayUseridTxt.getText();
       
       Person p = new Person();
       p.setUsername(newusername);
       p.setUsername(newpassword);
       p.setUsername(newnuid);
       p.setUsername(newuserid);
       
       JOptionPane.showMessageDialog(this, "User has been updated");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMButtonActionPerformed
        // TODO add your handling code here:
        userProcessArea.remove(this);
        CardLayout layout = (CardLayout)userProcessArea.getLayout();
        layout.previous(userProcessArea);
        
    }//GEN-LAST:event_BackMButtonActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = UserTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        var selectedPerson =(Person)model.getValueAt(selectedRowIndex, 0);
        
        displayUsernameTxt.setText(String.valueOf(selectedPerson.getUsername()));
        displayPasswordTxt.setText(String.valueOf(selectedPerson.getPassword()));
        displayNUIDTxt.setText(String.valueOf(selectedPerson.getNUID()));
        displayUseridTxt.setText(selectedPerson.getUserid());
        
    }//GEN-LAST:event_UpdateBtnActionPerformed
private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        model.setRowCount(0);
        for(Person vs: UserDirectory.getUserList()){
            Object[] row = new Object[4];
            
            row[0]= vs.getPassword();
            row[1]= vs.getNUID();
            row[2]= vs.getUserid();
            row[3] = vs.getUsername();
            model.addRow(row);
            
        }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackMButton;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTable UserTable;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JTextField displayNUIDTxt;
    private javax.swing.JTextField displayPasswordTxt;
    private javax.swing.JTextField displayUseridTxt;
    private javax.swing.JTextField displayUsernameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchIdTxt;
    // End of variables declaration//GEN-END:variables
}
